### ISSUE TITLE
[Bug] - Timeline Audio Play Button has a confusing image

### ISSUE THREAD

**Issue by nthState** [nthState/Haptrix#102]
# Timeline Audio Play Button has a confusing image

The timeline audio play button is a generic play button, however, it doesn't play the haptic per-se, it plays the audio in the haptic, there is an animation of the play head moving.

- [x] Replace the image with a play/music note symbol
- [ ] Optionally hide the button if there is no audio....does this cause other issues
- [x] Add a border around the button

# Platforms

What platforms does it affect:

- [ ] iOS
- [x] macOS
- [ ] Other

**Comment by nthState-Chris** [comment]
Released in v3.5.5+79
