### ISSUE TITLE
Add windows support or make the desktop version open source

### ISSUE THREAD

**Issue by nougator** [nthState/Haptrix#21]

**Comment by nthState** [comment]
I'm closing this ticket for now, I don't own a windows based computer so I couldn't even begin to program it natively.

**Comment by nougator** [comment]
VM or Boot camp

**Comment by nthState** [comment]
I guess that's a fair point about a VM, could you send me a link to Windows version of Apple's CoreHaptics please?

**Comment by nougator** [comment]
What?

**Comment by nthState** [comment]
For example, here's Apple's documentation on Core Haptics: https://developer.apple.com/documentation/corehaptics 

Do you know where Microsofts documentation is?

**Comment by nougator** [comment]
https://docs.microsoft.com/en-us/

**Comment by nthState** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.devices.haptics?view=winrt-19041

**Comment by nougator** [comment]
Hmm I didn't know that it was I thing.
