### ISSUE TITLE
[Feature Request] - Improve selection and dragging

### ISSUE THREAD

**Issue by nthState** [nthState/Haptrix#33]
julecom wrote: I would want to use the arrow icon to select and move elements (I don’t see the use of separating the arrow and the selection tool) and I would add a “hand” icon instead to move the canvas and use the Space bar + Drag command with any tool to move the canvas

**Comment by nthState** [comment]
@julecom I propose the following from your suggestions:
- New Hand tool, used for panning.
- Remove the dedicated selection tool and merge it into the Arrow tool
- Enhance the arrow tool to:
-- Add items
-- Move items
-- Option+Drag to select items
-- Optionally change the arrow to a cross-hair

**Comment by julecom** [comment]
Sounds perfect !! 
Also, would it possible to Move a continuous item by clicking and dragging anywhere on it and edit the duration by clicking on the top of a bracket on either side to make it shorter or longer ?

**Comment by nthState** [comment]
Hi @julecom, I've turned your above note into a new issue, you can do this in the timeline, but not in the editor yet (I don't know why I didn't add this, there must be a reason).

Regarding this ticket, It's fairly big so will release in 3.1.34

**Comment by nthState** [comment]
Released in 3.1
