### ISSUE TITLE
[Bug] - MacOS app crash

### ISSUE THREAD

**Issue by julecom** [nthState/Haptrix#35]
MacOS app crashes every time I click on the Play button
I'm on macOS Big Sur 11.4 - Haptrix v 3.0.8 (30)

**Comment by nthState** [comment]
Thanks @julecom I'm looking at this now, do you have a demo *.AHAP file & audio file I can use to help me debug it?

**Comment by nthState** [comment]
Update: I've managed to reproduce the crash, fix coming today

**Comment by nthState** [comment]
Until 3.0.9.31 is released, a workaround is to specify an audio file when using the in-editor audio player.

**Comment by nthState** [comment]
Released.
