### ISSUE TITLE
[Bug] - Can't select Haptric Transient bar

### ISSUE THREAD

**Issue by julecom** [nthState/Haptrix#36]
Can't select a Transient Haptic bar from the graph after adding a Continuous Haptic "on top of it"
Steps to reproduce:
- place a transient haptic bar (ex. at 0.5s)
- draw a continuous haptic from 0 to 1s 
- try to select and move the transient haptic

(macOs)

**Comment by nthState** [comment]
Hi @julecom - How would you like this to work?
I ask as the situation could be transient on top of continuous, or continuous on top of transient

It could work with multiple tapping, but that may not be the best UX

Any help welcome.

**Comment by julecom** [comment]
Hi! It would be instinctive to be able to hoover the mouse on any element and clicking to drag or edit no matter what "layer" they are on.. 
Basically the same comportment than Transient on top of continuous...

**Comment by nthState** [comment]
Fixed, will be released in 3.0.10.32

**Comment by nthState** [comment]
Released in 3.1
