### ISSUE TITLE
[Feature Request] Add ability to change continuous duration in designer view

### ISSUE THREAD

**Issue by nthState** [nthState/Haptrix#38]
Sounds perfect !! 
Also, would it be possible to Move a continuous item by clicking and dragging anywhere on it and edit the duration by clicking on the top of a bracket on either side to make it shorter or longer ?

_Originally posted by @julecom in https://github.com/nthState/Haptrix/issues/33#issuecomment-865985889_

**Comment by nthState** [comment]
Note:
You can already do this in the timeline

**Comment by julecom** [comment]
I know but I feel like the bottom Timeline is less precise for details (you can't zoom and there are no lines) and not very practical for the big picture while the main one is good for everything..

**Comment by nthState** [comment]
To recap, the current idea is to make the top of this bar selectable so that you can change the duration.

<img width="99" alt="Change duration" src="https://user-images.githubusercontent.com/6485463/123261299-7c70bc00-d4ee-11eb-9797-d5962a38e384.png">

**Comment by julecom** [comment]
It can be the whole bar (the flag looking element), when you put your mouse over the cursor would change  (like you did on the bottom timeline)

**Comment by nthState** [comment]
The first version of this has been released.
