### ISSUE TITLE
[Bug] - Crash when placing a Dynamic

### ISSUE THREAD

**Issue by julecom** [nthState/Haptrix#39]
Steps to reproduce:
- Place a dynamic on the timeline
- Click on the 'Play on device' icon

(macOS)

**Comment by nthState** [comment]
I really wish I knew, I support it simply because it's in Apples' Spec, however, I've never felt it work, I think it must be something to do with coding programmatically.

**Comment by nthState** [comment]
I'm going to roll this fix into 3.1.34

**Comment by nthState** [comment]
Released in 3.1
