### ISSUE TITLE
[Bug] - <Haptics with Audio are not auditionable>

### ISSUE THREAD

**Issue by nebosphere19** [nthState/Haptrix#53]
# Haptics with Audio are not auditionable

Short description of issue

- [When trying to upload a haptic with audio, it appears to upload, but then when accessing it I get an internal server error in the browser. It is also not possible to play it via the iOS app. I feel the pulses, but no sound comes out ] Bullet points if needed
- [ ] 
- [ ] 

# Detailed Description

A longer description of the issue

# Platforms

What platforms does it affect:

- [ X] iOS
- [ X] macOS
- [ ] Other

**Comment by nebosphere19** [comment]
Thanks for getting back to me!

Here's what I do, in screenshots. I create a haptic with sound and try and
upload it to the cloud(set to commercial and not publicly viewable):

[image: image.png]
After uploading:

[image: image.png]


I try and visit the URL it gives me and the result is:

[image: image.png]

**Comment by nthState** [comment]
@nebosphere19 It looks like the images haven't been attached, if it's easier, could you email me them to: contact@haptrix.com

Kind Regards
Chris

**Comment by nebosphere19** [comment]
Thanks! Strangely, it’s still saying “Generating, Please wait” It’s been almost an hour.

https://www.haptrix.com/content/testwithsound-by-ben-venturesonic-com



Also, it still does not play the audio in the haptic when previewing on my device via the sync function and the button on the far right of the toolbar : 

I feel the haptics on the phone/app but no sound comes through.

Thanks!
Ben

**Comment by nthState** [comment]
Re-opening

**Comment by nthState** [comment]
I've updated the server side generation.
The server was complaining that the audio file was 24-bit, the library I was using didn't support it, so I've updated it.
I've also re-generated the images.

I will note that the audio file is very quiet, even on my Mac I had to turn the volume all the way up to hear it.
So there is a chance it is playing, we just can't hear it

**Comment by nebosphere19** [comment]
Thanks… should it work in the iOS app when synced with the MacOS app now as well?

**Comment by nthState** [comment]
It should, is it not working? If so, can you check:
- If your phone is on silent mode
- If you can turn the volume all the way up to see if you can hear the audio

**Comment by nthState** [comment]
@nebosphere19 I have found the issue, sorry it isn't clear, I'll work on a fix now

```
HapticIntensity isn't a valid property on an audio event, however the audio event had a HapticIntensity set in the JSON, removing it fixed the problem
```

I'll work on a better UI and a system to strip invalid properties on sync/run

**Comment by nebosphere19** [comment]
Thank you!

Last questions: how can I see a list of the non-public haptics I’ve posted?

Can delete them?

Can I delete public ones I’ve posted? There appears to be no UI option for
this.

**Comment by nthState** [comment]
> Thank you! Last questions: how can I see a list of the non-public haptics I’ve posted? Can delete them? Can I delete public ones I’ve posted? There appears to be no UI option for this.
> […](#)

You can see all of your Haptics in the /myProfile/contents area of the website.

You're actually the first person to ask for this feature, I can add it, but will take a little more time.

**Comment by nebosphere19** [comment]
We are going to be doing development with proprietary sounds/patterns that are legally protected so we don’t want to leave things hanging around.

**Comment by nebosphere19** [comment]
Still cannot find a way to play haptics and hear sound on the iOS device at the same time. 

When I visit one of my haptic URLs using the app, this is what happens:

**Comment by nthState** [comment]
Hi, iOS 2.0.11 macOS 3.2.9 have now been released, could you please try your development with these versions?

please let me know if you get further issues.

I’ve added deletion as a separate feature request

Chris

**Comment by nebosphere19** [comment]
Thanks I’ll check these out tonight

**Comment by nebosphere19** [comment]
Seems it is still having the same problems:

The haptic will play on the iOS device, but no sound comes out and
The playback of the sound stops at the last haptic transient when I
audition it in the MacOS app.

**Comment by nebosphere19** [comment]
I also cannot load from URL in the iOS app. It just says "Could not load
external file"
