### ISSUE TITLE
[Bug] - Load from External not working for all users

### ISSUE THREAD

**Issue by ghost** [nthState/Haptrix#55]
# Load from External not working for all users

When loading a haptic from an external URL, the haptic doesn't always play

# Platforms

What platforms does it affect:

- [ ] iOS
- [ ] macOS
- [ ] Other

**Comment by nthState** [comment]
I've tested this by:

- Opening the Haptrix iOS App
- Tapping on External
- Pasting in the URL below
- Tapping load

The result is the haptic plays

```
https://raw.githubusercontent.com/nthState/Haptrix/main/Samples/Heartbeats.ahap
```
